version: "3.8"

services:
  sfusion-mapper:
    # Name of the image to be created or used
    image: sfusion-app
    
    # Instruct Docker to build the image using the Dockerfile in current folder
    build: .
    
    # Environment settings for graphical user interface (GUI)
    environment:
      # Pass the display monitor number (e.g. :0 or :1) from host to container
      - DISPLAY=${DISPLAY}
      
      # Fix required for Qt/PySide6 applications in Docker
      - QT_X11_NO_MITSHM=1
      
      # Force XCB (X11) plugin instead of Wayland
      - QT_QPA_PLATFORM=xcb
      
    # Map the Ubuntu X11 socket to container
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix